import { Command } from "commander";
import chalk from "chalk";
import { traceWhy, traceForward, computeCoverage } from "../../core/trace.js";
import { rebuildIndex } from "../../core/index-builder.js";

export const traceCommand = new Command("trace")
  .description("Traceability matrix operations");

traceCommand
  .command("why <file>")
  .description("Trace a file back to its spec ancestry")
  .action(async (file: string) => {
    const projectRoot = process.cwd();
    const ancestry = await traceWhy(projectRoot, file);

    if (!ancestry) {
      console.log(chalk.yellow(`No trace ancestry found for: ${file}`));
      console.log("This file may not have been generated by SPECTRA.");
      return;
    }

    console.log(chalk.bold("\nTrace Ancestry:\n"));
    console.log(`  File:          ${chalk.cyan(ancestry.file)}`);
    console.log(`  Spec:          ${chalk.green(ancestry.spec_id)}`);
    console.log(`  Spec Hash:     ${ancestry.spec_hash}`);
    if (ancestry.impl_ref) console.log(`  Impl Ref:      ${ancestry.impl_ref}`);
    if (ancestry.concern) console.log(`  Concern:       ${ancestry.concern}`);
    if (ancestry.generation_id) console.log(`  Generation ID: ${ancestry.generation_id}`);
    console.log();
  });

traceCommand
  .command("forward <spec-id>")
  .description("List all artifacts authorized by a spec")
  .action(async (specId: string) => {
    const projectRoot = process.cwd();
    const entry = await traceForward(projectRoot, specId);

    if (!entry) {
      console.log(chalk.yellow(`No trace entry found for: ${specId}`));
      return;
    }

    console.log(chalk.bold(`\nArtifacts for ${specId}:\n`));
    console.log(`  Status: ${entry.status}`);
    console.log(`  Hash:   ${entry.hash}`);

    if (entry.authorized_artifacts.length > 0) {
      console.log(`\n  Authorized Artifacts:`);
      for (const a of entry.authorized_artifacts) {
        console.log(`    ${chalk.cyan(a.path)} [${a.type}]`);
        if (a.concern) console.log(`      Concern: ${a.concern}`);
        if (a.impl_ref) console.log(`      Impl: ${a.impl_ref}`);
      }
    } else {
      console.log(chalk.yellow("\n  No authorized artifacts yet."));
    }

    // Show gates
    const gateEntries = Object.entries(entry.gates);
    if (gateEntries.length > 0) {
      console.log(`\n  Gates:`);
      for (const [phase, status] of gateEntries) {
        const color = status === "approved" ? chalk.green : status === "expired" ? chalk.red : chalk.yellow;
        console.log(`    ${phase.padEnd(15)} ${color(status)}`);
      }
    }

    console.log();
  });

traceCommand
  .command("coverage <spec-id>")
  .description("Show acceptance criteria test coverage")
  .action(async (specId: string) => {
    const projectRoot = process.cwd();
    const report = await computeCoverage(projectRoot, specId);

    if (!report) {
      console.log(chalk.yellow(`No coverage data for: ${specId}`));
      return;
    }

    console.log(chalk.bold(`\nAC Coverage for ${specId}:\n`));
    console.log(`  Total ACs:   ${report.total_acs}`);
    console.log(`  Covered:     ${report.covered_acs}`);
    console.log(`  Coverage:    ${report.coverage_percent}%`);

    if (report.uncovered.length > 0) {
      console.log(`\n  Uncovered ACs:`);
      for (const ac of report.uncovered) {
        console.log(`    ${chalk.red(ac)}`);
      }
    }
    console.log();
  });

traceCommand
  .command("update")
  .description("Rebuild the traceability index")
  .action(async () => {
    const projectRoot = process.cwd();
    await rebuildIndex(projectRoot);
    console.log(chalk.green("Traceability index updated."));
  });
